# Use root/example as user/password credentials
version: '3.1'

services:

  my-mongo-db:
    container_name: my-mongo-db
    image: mongo
    volumes:
      - ~/mongors/data:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker

networks:
  mongors-network:
    driver: bridge